import Head from 'next/head'
import Image from 'next/image'
import Post from '../components/Post/Post'
import PostForm from '../components/PostForm'
import Bio from '../components/Bio/Bio'
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <Bio 
        headshot="https://pbs.twimg.com/profile_images/1602029653614628873/6t81Fb31_400x400.jpg"
        name="Maddie Kessinger"
        tagline="Helping others learn by doing! "
        role="Full Stack Developer @ Unicode"
        />
        <ul className={styles.posts}>
          <li>
           <Post content={'This is new content'} date={'1/09/23'}/>
          </li>
          <li>
          <Post content='I’m working in Figma trying to design a new website that shows all of my tweets!' date='1/08/23'/>
          </li>
          <li>
            <Post content='I’m working in Figma trying to design a new website that shows all of my tweets!' date='1/08/23'/>
          </li>
        </ul>

        {/* <form>
          <textarea className={styles.formContent}></textarea>
          <button className={styles.formBtn}>Add New Post</button>
        </form> */}
        <PostForm/>

      </main>
    </div>
  )
}
